### PR TITLE
Add rconle WebUI

### PR DESCRIPTION
**Pull request by ich777**
Here is my long awaited PR for the rclone WebUI

You should be able to try this PR first by downloading the package that I've included in this PR, manually install it and running these commands from a Unraid Terminal before visiting the plugin page (because these are necessary and usually executed by the plugin file:
```
if [ ! -f /boot/config/plugins/rclone/settings.cfg ]; then
  echo "WEBUI_ENABLED=false
WEBUI_START_PARAMS=--rc-no-auth
WEBUI_PORT=5572" > /boot/config/plugins/rclone/settings.cfg
fi

/usr/local/emhttp/plugins/rclone/webuiScript.sh "VERSION"
```

After you've did that you can visit the plugin page and it should look something like that:
grafik

When you enable the WebUI you get a pop up:
grafik

After doing that the page is refreshed:
grafik

With a click on `Open WebUI` can finally get into the WebUI:
grafik
(or you simply open the browser and go to: `http://YOURUNRAIDIP:5572`

I hope that is suitable and something you want to integrate into your plugin. :)

### CODE REVIEW

**Comment by Waseh** [comment]
This looks great. Hopefully I'll have some time within the next week to test it out and get it merged.

**Comment by ich777** [comment]
@Waseh no worries, take your time...

Hope this is useful, I made it pretty simple to use, at least I think.

Oh, BTW do you mind making curl on boot quiet? It is a bit distracting in the console to always have a download indicator on boot.
Would you maybe consider switching over to `wget` instead since you can specify a timeout for the download and also a DNS timeout for really weird setups since I saw you made a fix for such systems.

**Comment by ich777** [comment]
@Waseh do you yet had time to look into the PR?
I use it now since I've issued it and it works perfectly fine from what I can tell on my server.

**Comment by Waseh** [comment]
@ich777 - Been fine in my testing and on my system as well.
Thank you very much for the contribution

**Comment by ich777** [comment]
> Adding a short sleep before the pgrep fixes it.

Oh that‘s unfortunate, I completely forgot to test this on my slower tester server which would have most likely shown the same behaviour.

Sorry about that… Maybe add a 2 second delay since this isn‘t veryuch of a delay anyways just to be on the safe side.

**Pull request merged**
